### ISSUE TITLE
OSX build

### ISSUE THREAD

**Issue by wenq1** [darsto/spookytom#11]
Just a quick try out, and found that it does not build on OSX. There seems to be some linux-specfics used, e.g. ".../" instead of "../../". A quick fix might be required if OSX support gets a chance to your list of goals?

```
venus:spooky wc$ mkdir -p build/android && cd build/android
venus:android wc$ cmake -DCMAKE_TOOLCHAIN_FILE=[...]/toolchain-android.cmake -DANDROID_ABI="armeabi" -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED=ON ../..
CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeDetermineSystem.cmake:104 (message):
```

**Comment by darsto** [comment]
It should build fine on OSX, however it was never tested.
_[...]_ should be replaced with the actual path by the user. I forgot to mention it in the installation guide, I'll add it right away. Thanks

**Comment by darsto** [comment]
I replaced all [...] in INSTALL.md with "/path/to", so that nobody will get confused.
